---
prometheus:
  scrapeAnnotations: true
  serviceAccount: "monitoring-prometheus-kube-prometheus"
  namespace: monitoring
  podMonitor:
    enabled: false
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: true
