---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: prowlarr-config-dst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: prowlarr-config-volsync-backblaze-secret
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 1Gi
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    capacity: 5Gi
    moverSecurityContext:
      runAsNonRoot: true
      runAsGroup: 65534
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
