[tool.poetry]
name = "homelab"
version = "0.1.0"
description = ""
authors = ["Craig Davis <11911367+blade2005@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^10.1.0"
kubernetes = "^30.1.0"
boto3 = "^1.34.143"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^24.6.1", markers = "platform_system != 'Windows'" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
