---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-provisioner
helmCharts:
  - name: local-path-provisioner
    namespace: local-path-provisioner
    repo: https://charts.containeroo.ch
    releaseName: local-path-provisioner
    version: 0.0.34
    includeCRDs: true
    valuesFile: values.yaml
