---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
helmCharts:
  - name: volsync
    includeCRDs: true
    repo: https://backube.github.io/helm-charts/
    namespace: volsync
    releaseName: volsync
    version: 0.13.1
    valuesFile: values.yaml
resources:
  - prometheus-rule.yaml
