---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://helm.openwebui.com"
    targetRevision: 3.0.4
    chart: open-webui
    helm:
      valuesObject:
        extraEnvVars:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: open-ai-api-key
                key: api-key
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
