---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: jellyfin-library-nfs
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-ip
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: "10.49.49.140/library##"
    volumeAttributes:
      server: 10.49.49.140
      share: /library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-library-nfs
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Ti
  storageClassName: nfs
  volumeName: jellyfin-library-nfs
