---
image:
  repository: docker.dragonflydb.io/dragonflydb/dragonfly
  # renovate: datasource=docker depName=docker.dragonflydb.io/dragonflydb/dragonfly
  tag: "v1.34.2"
storage:
  enabled: true
  requests: 10Gi # Set a desired volume size for PVC.
extraArgs:
  - --dbfilename=my-dump-{timestamp} # Only the filename without any file extensions.
  - --snapshot_cron=10 * * * * # Set a valid cron schedule.

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

  runAsNonRoot: true
  runAsUser: 1000
