[project]
name = "faerun-pulumi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0, <4.0.0"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=7.0.0,<8.0.0",
    "pulumi-std>=2.2.0",
]
