---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: csi-driver-nfs
    namespace: kube-system
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    releaseName: csi-driver-nfs
    version: 4.9.0
    includeCRDs: true
    valuesFile: values.yaml
