---
controller:
  replicas: 1
  dnsPolicy: Default
storageClass:
  create: true
  name: nfs
  parameters:
    server: storage-0001.stoneydavis.local
    share: /library
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1
node:
  dnsPolicy: Default
