---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: readarr
helmCharts:
  - name: cloudflare-tunnel
    repo: https://cloudflare.github.io/helm-charts
    namespace: readarr
    releaseName: readarr
    version: 0.3.2
    valuesFile: cloudflare-values.yaml
  - name: app-template
    includeCRDs: true
    repo: https://bjw-s-labs.github.io/helm-charts
    namespace: readarr
    releaseName: readarr
    version: 4.6.2
    valuesFile: values.yaml
resources:
  - ./volsync-external-secret.yaml
  - ./volsync-replication-source.yaml
  - ./volsync-replication-destination.yaml
  - ./external-secret.yaml
