---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mikrotik-credentials
    creationPolicy: Owner
  data:
    - secretKey: base-url
      remoteRef:
        key: mikrotik-router/base-url
    - secretKey: username
      remoteRef:
        key: mikrotik-router/username
    - secretKey: password
      remoteRef:
        key: mikrotik-router/password
    - secretKey: tls-verify
      remoteRef:
        key: mikrotik-router/tls-verify
