---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
helmCharts:
  - name: volsync
    includeCRDs: true
    repo: https://backube.github.io/helm-charts/
    namespace: system
    releaseName: volsync
    version: 0.9.1
resources:
  - prometheus-rule.yaml
