---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
# The singleton is any already running k3s controlplane node.  Mostly we
# just need to have the correct node token to use on any other control
# plane node, because we initialize everything on the first one and then
# all other control plane nodes will join on the running node for the
# initial setup.
#
# Otherwise they won't be able to communicate and you'd have three
# isolated control planes, not a single HA control plane.
- name: singleton | Copy Jinja template
  ansible.builtin.template:
    src: singleton.config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0600"
- name: singleton | Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: "0644"
- name: singleton | Copy kubelet.config
  ansible.builtin.template:
    src: kubelet.config.j2
    dest: /etc/rancher/k3s/kubelet.config
    owner: root
    group: root
    mode: "0600"
- name: singleton | Enable and check K3s service
  any_errors_fatal: true
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true
- name: singleton | Wait for node-token
  ansible.builtin.wait_for:
    path: "{{ k3s_server_location }}/server/node-token"
- name: singleton | Register node-token file access mode
  ansible.builtin.stat:
    path: "{{ k3s_server_location }}/server/node-token"
  register: p
- name: singleton | Change file access node-token
  ansible.builtin.file:
    path: "{{ k3s_server_location }}/server/node-token"
    mode: g+rx,o+rx
- name: singleton | Read node-token from master
  ansible.builtin.slurp:
    path: "{{ k3s_server_location }}/server/node-token"
  register: node_token
- name: singleton | Store Master node-token and IP address
  ansible.builtin.set_fact:
    k3s_master_token: "{{ node_token.content | b64decode | regex_replace('\n', '')
      }}"
- name: singleton | Restore node-token file access
  ansible.builtin.file:
    path: "{{ k3s_server_location }}/server/node-token"
    mode: "{{ p.stat.mode }}"
- name: singleton | Wait for k3s to stabilize
  ansible.builtin.wait_for:
    port: 6443
    delay: 10
    timeout: 300
    state: started
- name: Get list of certs
  ansible.builtin.find:
    paths: /var/lib/rancher/k3s/server/tls
    patterns: "*.crt"
  register: controlplane_k3s_certs
- name: Chmod 0600 /var/lib/rancher/k3s/server/tls/*.crt
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0600'
  with_items: "{{ controlplane_k3s_certs.files }}"
