---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
helmCharts:
  - name: app-template
    includeCRDs: true
    repo: https://bjw-s-labs.github.io/helm-charts
    namespace: home-assistant
    releaseName: piper
    version: 4.6.2
    valuesFile: values.yaml
