---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpackerr-svc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: app-template
    targetRevision: 3.2.1
    helm:
      valuesObject:
        defaultPodOptions:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 1001
        controllers:
          main:
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: ghcr.io/hotio/unpackerr
                  tag: latest
                  pullPolicy: IfNotPresent
                env:
                  TZ: UTC
                  PUID: 1001
                  PGID: 1001
                  UMASK: "022"
                  UN_SONARR_0_URL: http://sonarr-app.homelab.svc.cluster.local
                  UN_SONARR_0_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: radarr-secret
                        key: api_key
                  UN_RADARR_0_URL: http://radarr-svc.homelab.svc.cluster.local
                  UN_RADARR_0_API_KEY:
                    valueFrom:
                      secretKeyRef:
                        name: radarr-secret
                        key: api_key
                  UN_INTERVAL: 2m
                  UN_START_DELAY: 1m
                  UN_RETRY_DELAY: 5m
                  UN_MAX_RETRIES: 3
                  UN_PARALLEL: 1
                  UN_FILE_MODE: "0644"
                  UN_DIR_MODE: "0755"
                  # Sonarr Config
                  UN_SONARR_0_PATHS_0: /library/downloads/done/sonarr
                  UN_SONARR_0_PROTOCOLS: torrent
                  UN_SONARR_0_TIMEOUT: 10s
                  UN_SONARR_0_DELETE_ORIG: "false"
                  UN_SONARR_0_DELETE_DELAY: 5m
                  # Radarr Config
                  UN_RADARR_0_PATHS_0: /library/downloads/done/radarr
                  UN_RADARR_0_PROTOCOLS: torrent
                  UN_RADARR_0_TIMEOUT: 10s
                  UN_RADARR_0_DELETE_ORIG: "false"
                  UN_RADARR_0_DELETE_DELAY: 5m
                  # Lidarr Config
                  UN_LIDARR_0_PATHS_0: /library/downloads/done/lidarr
                  UN_LIDARR_0_PROTOCOLS: torrent
                  UN_LIDARR_0_TIMEOUT: 10s
                  UN_LIDARR_0_DELETE_ORIG: "false"
                  UN_LIDARR_0_DELETE_DELAY: 5m
                  # Readarr Config
                  UN_READARR_0_PATHS_0: /library/downloads/done/readarr
                  UN_READARR_0_PROTOCOLS: torrent
                  UN_READARR_0_TIMEOUT: 10s
                  UN_READARR_0_DELETE_ORIG: "false"
                  UN_READARR_0_DELETE_DELAY: 5m
                  # Folder Config
                  UN_FOLDER_0_PATH: /library/downloads/done/no-label
                  UN_FOLDER_0_EXTRACT_PATH:
                  UN_FOLDER_0_DELETE_AFTER: 10m
                  UN_FOLDER_0_DELETE_ORIGINAL: "false"
                  UN_FOLDER_0_DELETE_FILES: "false"
                  UN_FOLDER_0_MOVE_BACK: "false"
                  # Webhook Config
                  UN_WEBHOOK_0_URL: https://notifiarr.com/api/v1/notification/unpackerr/b2c77ff1-38ae-4aea-96b7-e99319d76226
                  UN_WEBHOOK_0_NAME: Notifiarr
                  UN_WEBHOOK_0_NICKNAME: Unpackerr
                  UN_WEBHOOK_0_CHANNEL: ""
                  UN_WEBHOOK_0_TIMEOUT: 10s
                  UN_WEBHOOK_0_SILENT: "false"
                  UN_WEBHOOK_0_IGNORE_SSL: "false"
                  UN_WEBHOOK_0_EXCLUDE: "[]"
                  UN_WEBHOOK_0_EVENTS: "[0]"
        persistence:
          config:
            enabled: true
            storageClass: ceph-filesystem
            accessMode: ReadWriteOnce
            size: 1Gi
          library:
            enabled: true
            type: hostPath
            hostPathType: Directory
            hostPath: /library
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homelab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
