---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-controllers
helmCharts:
  - name: snapshot-controller
    namespace: system-controllers
    releaseName: snapshot-controller
    repo: https://piraeus.io/helm-charts/
    version: 5.0.2
    includeCRDs: false
    valuesFile: values.yaml
resources:
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=master
