---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba-svc
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behavior is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: samba-app
spec:
  project: default
  source:
    repoURL: https://github.com/iMartyn/helm-samba4.git
    targetRevision: master
    chart: samba4
    helm:
      valuesObject:
        samba:
          users:
            - username: otherUser
              password: CorrectBatteryHorseStaple256487
        persistence:
          enabled: true
          pvc:
            hostPath:
              path: /library
        privatePersistence:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homelab
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
